name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Chạy mỗi 12 giờ
  workflow_dispatch:        # Cho phép chạy thủ công từ GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: datyounger
          outputs: |
            dist/snake-dark.svg?palette=github-dark&color_snake=#ffffff

      - name: Check if snake file exists
        run: |
          if [ ! -f dist/snake-dark.svg ]; then
            echo "Snake file not found!"
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist
          if-no-files-found: warn
